audio_folder: data/musics/
chord_detection:
  hop_length: 384
  onset_delta: 0.75
  sensitivity: 0.78
logger:
  console_level: WARNING
  file_level: DEBUG
merge_instrumental: true
noise_removal:
  enabled: true
  level: 0.4
output_folder: data/outputs/
transcription:
  model: small
