audio_folder: data/musics/
chord_detection:
  hop_length: 448
  onset_delta: 0.11
  sensitivity: 0.96
logger:
  console_level: WARNING
  file_level: DEBUG
noise_removal:
  enabled: true
  level: 0.4
output_folder: data/outputs/
transcription:
  model: medium
