audio_folder: data/musics/
chord_detection:
  hop_length: 256
  onset_delta: 0.08
  sensitivity: 0.58
logger:
  console_level: WARNING
  file_level: DEBUG
noise_removal:
  enabled: true
  level: 0.4
output_folder: data/outputs/
transcription:
  model: small
