audio_folder: data/musics/
chord_detection:
  hop_length: 320
  onset_delta: 0.73
  sensitivity: 0.71
logger:
  console_level: WARNING
  file_level: DEBUG
merge_instrumental: true
noise_removal:
  enabled: true
  level: 0.4
output_folder: data/outputs/
transcription:
  model: small
